### ISSUE TITLE
Inhibitor doesn't seem to be working

### ISSUE THREAD

**Issue by SplittyDev** [1Computer1/discord-akairo#13]
Hey, I wrote a very simple inhibitor, and if I understand the documentation correctly, the following code should prevent all messages containing 'test' from appearing in the channel:

```js
const {Inhibitor} = require('discord-akairo');
class RoombaInhibitor extends Inhibitor {
    constructor() {
        super('roomba', {
            reason: 'Roomba!',
            type: 'all',
        });
    }
    exec(message) {
        return message.content.toLowerCase().includes('test');
    }
}
module.exports = RoombaInhibitor;
```

I verified that the `exec` method returns `true`, but the message still shows up.
Is this the expected behavior? If so, the documentation doesn't make it clear.

If not, any idea how to fix this?

**Comment by TeeSeal** [comment]
The inhibitors are not meant to prevent messages from appearing in channels, they are meant to prevent the bot from processing them. You would use an inhibitor to make sure someone can't use commands, or so that commands are not used in a particular channel.

**Comment by SplittyDev** [comment]
@TeeSeal Oh okay, thank you
How would I listen for messages and selectively remove some messages then?
I couldn't find a way to just listen for messages, and I also couldn't find anything about deleting messages in the documentation.

**Comment by TeeSeal** [comment]
The framework blocks all messages that don't start with the prefix by default.

To do what you intend to do you would have to write your own `message` listener and handle that in there.
