### ISSUE TITLE
Provide testing utilities

### ISSUE THREAD

**Issue by OzairP** [1Computer1/discord-akairo#14]
Would be nice if we could mock commands and users so we can unit test our bots.
Possibly expose methods to invoke commands with mocked data.

**Comment by 1Computer1** [comment]
This is already possible, one such method could be building the modules without logging in then interacting with those modules, e.g.
```js
client.commandHandler.modules.get('roll').exec({
    // Mocks a message
    send(content) {
        console.log(content);
    }
}, {
  // Mocks args
  faces: 6
})
```
Another method could be emitting the events you want to test, such as the message event.
If you mean more than this, such as simulating entire guilds and users to work with, then you would have to bring the issue to discord.js.

**Comment by OzairP** [comment]
That's great, thanks. You should add this into the gitbook as well.
