### ISSUE TITLE
Exclude files/folders in command directory

### ISSUE THREAD

**Issue by astraldragon** [1Computer1/discord-akairo#15]
One of the recommended patterns for organizing jest unit tests is to have a __tests__ folder alongside the files you want to test.  This style doesn't seem to work when registering my command folder.  Discord Commando lets you pass in an exclusion rule when importing your files.  This is what I have currently set up in Commando.

```js
.registerCommandsIn({
  dirname: path.join(__dirname, "commands"),
  excludeDirs: /^__tests__$/
});
```

**Comment by 1Computer1** [comment]
Implemented in 03805445a3feef113c2b6f1711f1adb46f4ac40a
