### ISSUE TITLE
MongoDB Support?

### ISSUE THREAD

**Issue by FireController1847** [1Computer1/discord-akairo#17]
I don't know, since you support SQLite and Sequelize I just thought it'd be kind of handy to also support MongoDB. :)

**Comment by Loganrose** [comment]
And RethinkDB

**Comment by FireController1847** [comment]
I might take a shot at PRing this for Mongo, never used React though so not sure on that one.

**Comment by Loganrose** [comment]
... its Rethink. React is a front-end framework

**Comment by FireController1847** [comment]
My phone autocorrected that sorry... I remember typing Rethink lol

**Comment by 1Computer1** [comment]
Most probably not going to be added due to its low usage compared to SQLite and Sequelize, but you are free to keep a fork.
