### ISSUE TITLE
Postgres Support?

### ISSUE THREAD

**Issue by Strikerrr** [1Computer1/discord-akairo#20]
Is there any way to implement postgres into this or can you do that with the in-built sequelize provider?

**Comment by RyoshiKayo** [comment]
> Sequelize is a promise-based ORM for Node.js and io.js. It supports the dialects PostgreSQL, MySQL, MariaDB, SQLite and MSSQL and features solid transaction support, relations, read replication and more.

http://sequelize.readthedocs.io/en/v3/

**Comment by Strikerrr** [comment]
Oh right so in the code example from the docs I'd just do this
```js
this.settings = new SequelizeProvider('link to PG database', {
            idColumn: 'guild_id',
            dataColumn: 'settings'
        });
```

would pg need to be installed as a dependency as well?

**Comment by RyoshiKayo** [comment]
Yes you would have to install and set up a PostgreSQL server, it isn't like SQLite3.

**Comment by Strikerrr** [comment]
Alright thanks
