### ISSUE TITLE
List of events

### ISSUE THREAD

**Issue by Strikerrr** [1Computer1/discord-akairo#21]
Hi, is there a list of events in the docs? If so, where?
Thanks.

**Comment by Strikerrr** [comment]
I'm particularly looking for what event is emitted when a command fails due to args not being parsed etc

**Comment by Strikerrr** [comment]
Or if a command just fails in general

**Comment by 1Computer1** [comment]
Handler events are available at the end of their page.
https://1computer1.github.io/discord-akairo/CommandHandler.html, `messageInvalid` or `error` is what you're looking for.

**Comment by Strikerrr** [comment]
Thanks!
