### ISSUE TITLE
SequelizeProvider and SQLiteProvider delete() function does not update cached data

### ISSUE THREAD

**Issue by Jovin-Ang** [1Computer1/discord-akairo#42]
The delete() function present in both providers deletes the key value specified and affects the database but does not update the cached data.
For example, `this.client.settings(message.guild.id, "prefix")` returns `!`
After `this.client.settings.delete(message.guild.id, "prefix")`,
when running  `this.client.settings(message.guild.id, "prefix")`, still returns `!`
However, in the actual database, the value is already deleted, just that the local cached storage is not updated.

**Comment by 1Computer1** [comment]
`delete` is asynchronous, have you made sure that you awaited the resulting Promise?

**Comment by Jovin-Ang** [comment]
I have solved my issue by setting a null value on the key i want to delete. I presume delete doesn't work for me cause i handled the whole table instead of just a json column. Deleting a column is impossible.
