### ISSUE TITLE
ArgumentMatch type rest no longer ignores phrases that match a flag

### ISSUE THREAD

**Issue by aiospos** [1Computer1/discord-akairo#43]
This occurred to me not too long ago, figured I did something wrong, 
my client who apparanently ran npm i just yesterday had all the commands with ArgumentMatch rest stop working, this obviously confirms that I wasn't wrong and there's something with the arguments being parsed.

**Comment by 1Computer1** [comment]
Hello, please provide your version (i.e. commit hash) and a minimal reproducible example.

**Comment by aiospos** [comment]
sorry daddy
