### ISSUE TITLE
Date arguments are assumed to be in the server's timezone

### ISSUE THREAD

**Issue by Benny-** [1Computer1/discord-akairo#9]
Reproducible steps:
- Make a command which needs a date.
- Execute that command with for example "2017-07-16 21:00"

Expected result:
Printing the date in the command handler results in "2017-07-16T21:00:00.000Z"

Actual result:
Printing the date in the command handler results in "2017-07-16T19:00:00.000Z" (My timezone is +2 hours)

Rationale:
The timezone of the server has mostly no relation with the user who issued the command.

Some of my code with everything unrelated removed (not yet run):
```javascript
"use strict";

const { Command } = require('discord-akairo');

class DateCommand extends Command {
    constructor() {
        super('date', {
            aliases: ['date'],
            cooldown: 5000,
            ratelimit: 10,
            split: 'sticky',
            args: [
                {
                    id: 'date',
                    type: 'date',
                }
            ]
        });
    }

    exec(message, args) {
        let date = args.date
        console.log(date)
        
        return Promise.resolve()
    }
};

module.exports = DateCommand

```

**Comment by 1Computer1** [comment]
That's just how `Date.parse` works. You can make it do what you want by adding "Z" to the end of the input. But, there are many different formats for how dates can get parsed so I cannot assume that in the library.
